name: M3U Otomatik Birlestirici
on:
  schedule:
    - cron: '0 0 * * *' # Her gece otomatik çalışır
  workflow_dispatch: # Elle çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v4

      - name: Kanalları ve Calısan İsvicre Listesini Birlestir
        run: |
          echo "#EXTM3U" > hepsi.m3u
          curl -s "https://githubusercontent.com" | sed '1d' >> hepsi.m3u
          curl -s "https://githubusercontent.com" | sed '1d' >> hepsi.m3u
          curl -s "https://githubusercontent.com" | sed '1d' >> hepsi.m3u
          curl -s "https://githubusercontent.com" | sed '1d' >> hepsi.m3u
          curl -s "https://githubusercontent.com" | sed '1d' >> hepsi.m3u
          curl -s "https://iptv-org.github.io/iptv/countries/ch.m3u" | sed '1d' >> hepsi.m3u

      - name: Degisiklikleri Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add hepsi.m3u
          git diff-index --quiet HEAD || git commit -m "Tum Kanallar Tamamen Calısır Durumda"
          git push
