name: M3U Otomatik Birlestirici
on:
  schedule:
    - cron: '0 0 * * *' # Her gece otomatik çalışır
  workflow_dispatch: # Elle çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v4

      - name: Kanalları Tek Dosyada Kusursuz Birlestir
        run: |
          echo "#EXTM3U" > hepsi.m3u
          
          # 1. Adım: p.m3u dosyanın içindeki o çalışan 5 linki sırayla okuyup içeriği çekiyoruz
          while IFS= read -r link || [ -n "$link" ]; do
            if [ ! -z "$link" ]; then
              curl -s "$link" | sed '1d' >> hepsi.m3u
            fi
          done < p.m3u
          
          # 2. Adım: isvicre.m3u dosyanın içindeki o senin çalışan İsviçre adresini okuyup içeriği çekiyoruz
          ISVICRE_LINK=$(cat isvicre.m3u)
          if [ ! -z "$ISVICRE_LINK" ]; then
            curl -s "$ISVICRE_LINK" | sed '1d' >> hepsi.m3u
          fi

      - name: Degisiklikleri Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add hepsi.m3u
          git diff-index --quiet HEAD || git commit -m "Tum kanallar deponun duzenine gore birlestirildi"
          git push
